import { useMemo, useState } from 'react'
import QRCode from 'react-qr-code'
import { ArrowRight, Check, ChevronRight, ClipboardCheck, FileScan, GitBranch, QrCode, ScanLine, Sparkles } from 'lucide-react'

type Field = { id: string; label: string; value: string; source: string; note: string }
const fields: Field[] = [
  { id: 'part', label: 'Part number', value: 'AGP-78421', source: 'A1 · title block', note: 'Released manufacturing identifier' },
  { id: 'rev', label: 'Revision', value: 'C', source: 'A1 · title block', note: 'ECN-2196 · 18 JUL 2026' },
  { id: 'material', label: 'Material', value: '6061-T6 ALUMINUM', source: 'C3 · general note 1', note: 'ASTM B221 · certification required' },
  { id: 'finish', label: 'Finish', value: 'CLEAR ANODIZE — TYPE II', source: 'C4 · general note 2', note: 'MIL-A-8625 · class 1' },
  { id: 'bore', label: 'Critical bore', value: '⌀ 1.2500 ± .0005 IN', source: 'B2 · detail A', note: 'CTQ · inspect 100%' },
  { id: 'length', label: 'Overall length', value: '4.875 ± .010 IN', source: 'B3 · main view', note: 'Machined overall dimension' },
  { id: 'surface', label: 'Surface finish', value: '32 µIN Ra MAX', source: 'C5 · general note 3', note: 'Applies unless noted otherwise' },
]
const nodes = [
  { id: 'part', x: 50, y: 44, label: 'AGP-78421', type: 'Part', detail: 'Clevis adapter · released' }, { id: 'drawing', x: 19, y: 20, label: 'DWG 78421-C', type: 'Drawing', detail: '1 page · revision C' },
  { id: 'material', x: 77, y: 18, label: '6061-T6', type: 'Material', detail: 'ASTM B221' }, { id: 'supplier', x: 84, y: 68, label: 'Mason Metal', type: 'Supplier', detail: 'Approved mill source' },
  { id: 'job', x: 18, y: 74, label: 'JOB-2417', type: 'Job', detail: '26 pieces · in process' }, { id: 'revision', x: 52, y: 80, label: 'REV C', type: 'Revision', detail: 'ECN-2196' },
  { id: 'spec', x: 54, y: 14, label: 'ANODIZE II', type: 'Process spec', detail: 'MIL-A-8625 class 1' },
]
const edges: [string, string][] = [['part','drawing'],['part','material'],['part','supplier'],['part','job'],['part','revision'],['part','spec'],['drawing','revision'],['material','supplier']]

function Drawing({ active }: { active: string }) {
  const chosen = active === 'part' || active === 'rev' ? 'title' : ['material','finish','surface'].includes(active) ? 'notes' : active === 'bore' ? 'detail' : 'main'
  const region = (name: string) => `source-region ${chosen === name ? 'is-active' : ''}`
  return <svg className="drawing" viewBox="0 0 920 610" role="img" aria-label="Illustrative released machining drawing for AGP-78421 clevis adapter">
    <defs><pattern id="draft-grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M10 0H0V10" fill="none" stroke="currentColor" strokeWidth=".6" /></pattern><marker id="arrowhead" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto-start-reverse"><path d="M0 0L6 3L0 6z" fill="currentColor" /></marker></defs>
    <rect width="920" height="610" fill="#f4f0e4" /><rect width="920" height="610" fill="url(#draft-grid)" opacity=".24" />
    <g className="drawing-ink"><text x="36" y="38" className="stamp">ARCH GP · RELEASED MANUFACTURING DRAWING · ILLUSTRATIVE DEMO DATA</text><path d="M198 174h334l40 40v120l-40 40H198l-40-40V214z" className="part-line" /><circle cx="307" cy="274" r="62" className="part-line" /><circle cx="307" cy="274" r="29" className="part-line" /><path d="M369 274h168M369 232h144M369 316h144M472 214v120M513 214v120" className="part-line" /><path d="M160 426h415M148 192v163M280 202v141" className="dimension" markerStart="url(#arrowhead)" markerEnd="url(#arrowhead)" /><path d="M160 374v60M575 374v60M148 192h50M148 355h50M280 202h57M280 343h57" className="extension" /><text x="330" y="451" className="dimension-text">4.875 ± .010</text><text x="92" y="298" transform="rotate(-90 92 298)" className="dimension-text">1.625 ± .005</text><text x="211" y="202" className="dimension-text">⌀ 1.2500 ± .0005</text><text x="415" y="187" className="detail-label">DETAIL A</text></g>
    <g className="notes-block"><rect x="641" y="109" width="237" height="176" /><text x="656" y="136" className="block-title">GENERAL NOTES</text><text x="656" y="164">1. MATERIAL: 6061-T6 ALUMINUM PER ASTM B221</text><text x="656" y="190">2. FINISH: CLEAR ANODIZE, TYPE II, CLASS 1</text><text x="656" y="216">3. SURFACE FINISH: 32 µIN Ra MAX</text><text x="656" y="242">4. BREAK ALL SHARP EDGES .010 MAX</text><text x="656" y="265">5. REMOVE ALL BURRS</text></g>
    <g className="title-block"><rect x="625" y="385" width="253" height="174" /><path d="M625 421h253M625 458h253M625 495h253M625 532h253" /><text x="639" y="407" className="block-title">ARCH GP MANUFACTURING</text><text x="639" y="444">PART NO.</text><text x="744" y="444" className="block-value">AGP-78421</text><text x="639" y="481">TITLE</text><text x="708" y="481">CLEVIS ADAPTER</text><text x="639" y="518">MATERIAL</text><text x="708" y="518">6061-T6 AL</text><text x="639" y="550">REV C</text><text x="759" y="550">SHEET 1 / 1</text></g>
    <g className={region('title')}><rect x="618" y="378" width="267" height="188" /><text x="620" y="370">A1 · TITLE BLOCK</text></g><g className={region('detail')}><circle cx="307" cy="274" r="76" /><text x="201" y="158">B2 · CRITICAL BORE</text></g><g className={region('main')}><rect x="148" y="151" width="442" height="286" /><text x="149" y="142">B3 · MAIN VIEW</text></g><g className={region('notes')}><rect x="634" y="102" width="251" height="190" /><text x="636" y="94">C3–C5 · GENERAL NOTES</text></g>
  </svg>
}
function Graph({ selected, setSelected }: { selected: string; setSelected: (id: string) => void }) {
  const selectedNode = nodes.find(node => node.id === selected) ?? nodes[0]
  return <><div className="graph-stage" aria-label="Second brain relationship graph"><svg className="graph-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{edges.map(([a,b],i) => { const from=nodes.find(n=>n.id===a)!; const to=nodes.find(n=>n.id===b)!; return <line key={i} x1={from.x} y1={from.y} x2={to.x} y2={to.y} className={selected===a||selected===b?'line-active':''} /> })}</svg>{nodes.map(node=><button key={node.id} className={`graph-node ${node.id===selected?'selected':''}`} style={{left:`${node.x}%`,top:`${node.y}%`}} onClick={()=>setSelected(node.id)} aria-pressed={node.id===selected}><span>{node.label}</span><small>{node.type}</small></button>)}</div><div className="graph-detail"><span className="entity-dot" /><strong>{selectedNode.label}</strong><span>{selectedNode.type}</span><p>{selectedNode.detail}</p></div><div className="link-legend"><span><i className="dot part" /> part</span><span><i className="dot context" /> context</span><span><i className="dot revision" /> revision</span></div></>
}
function App() {
  const [activeField,setActiveField]=useState('bore'); const [selectedNode,setSelectedNode]=useState('part'); const [qrOpen,setQrOpen]=useState(false)
  const url=useMemo(()=>typeof window==='undefined'?'https://arch-gp-demo.vercel.app/?part=AGP-78421':`${window.location.origin}${window.location.pathname}?part=AGP-78421`,[]); const active=fields.find(f=>f.id===activeField)!
  return <main><header className="topbar"><a className="wordmark" href="#top" aria-label="Arch GP demo home"><span>ARCH</span><i />GP <small>systems demo</small></a><nav><a href="#workbench">Workbench</a><a href="#qr">QR trace</a><a href="#loop">Maintenance loop</a></nav><button className="qr-trigger" onClick={()=>setQrOpen(v=>!v)} aria-expanded={qrOpen}><QrCode size={16} /> Part QR</button></header>
  {qrOpen&&<section className="qr-popover" aria-label="QR code for AGP-78421"><QRCode value={url} size={156} bgColor="#f6f4ee" fgColor="#162927" /><div><strong>AGP-78421</strong><p>Scan to resolve this part in the demo.</p><button onClick={()=>setQrOpen(false)}>Close</button></div></section>}
  <section id="top" className="masthead"><div><p className="kicker">One artifact. Two useful systems.</p><h1>From shop drawing<br />to shared knowledge.</h1><p className="intro">A machining drawing becomes a traceable spec record and a living visual second brain — from the same scan.</p></div><div className="fork-map" aria-label="One drawing forks into direct specifications and a linked second brain"><div className="input-chip"><FileScan /><span>AGP-78421<br /><small>released drawing</small></span></div><div className="fork-lines"><i /><i /></div><div className="output-stack"><span><ClipboardCheck /> Direct specs</span><span><GitBranch /> Second brain</span></div></div></section>
  <section id="workbench" className="workbench"><div className="panel-heading"><div><p className="kicker">Worked example · illustrative demo data</p><h2>AGP-78421 · Clevis adapter</h2></div><div className="status"><Check size={14} /> Extraction reviewed</div></div><div className="workbench-grid"><article className="drawing-pane"><div className="pane-label"><span><ScanLine size={17} /> Input artifact</span><small>DWG-78421-C · PDF scan</small></div><Drawing active={activeField}/><div className="trace-caption"><span className="target-mark" /> Selected field traces to <strong>{active.source}</strong></div></article><div className="fork-rail" aria-hidden="true"><span>ONE SCAN</span><i /><i /><b><ArrowRight /></b></div><article className="spec-pane"><div className="pane-label"><span><ClipboardCheck size={17} /> Direct specs</span><small>structured record</small></div><div className="spec-intro"><div><strong>{active.label}</strong><p>Click any field to locate its drawing source.</p></div><span className="confidence">98.7% read</span></div><div className="field-list">{fields.map(field=><button key={field.id} className={`field ${activeField===field.id?'active':''}`} onClick={()=>setActiveField(field.id)}><span><b>{field.label}</b><small>{field.source}</small></span><strong>{field.value}</strong><em>{field.note}</em></button>)}</div><div className="export-strip"><span>Export ready</span><b>CSV · XLSX · JSON</b><ChevronRight size={16}/></div></article><article className="brain-pane"><div className="pane-label"><span><GitBranch size={17} /> Visual second brain</span><small>7 entities · 8 links</small></div><p className="brain-copy">The same extraction adds context: suppliers, jobs, material, process, and revision history.</p><Graph selected={selectedNode} setSelected={setSelectedNode}/></article></div></section>
  <section id="qr" className="qr-section"><div className="qr-copy"><p className="kicker">The physical-to-digital path</p><h2>A code on the part resolves the whole record.</h2><p>Place this QR on a traveler, fixture, or bag label. It opens the same part record: its current direct specs and everything linked around it.</p><button onClick={()=>setQrOpen(true)}><QrCode size={17}/> Open part QR</button></div><div className="qr-card"><QRCode value={url} size={178} bgColor="#e9eee9" fgColor="#162927"/><div><span>PART IDENTIFIER</span><strong>AGP-78421</strong><small>Clevis adapter · Rev C</small></div></div><div className="qr-flow"><span>Scan</span><ArrowRight/><span>Part record</span><ArrowRight/><span>Specs + links</span></div></section>
  <section id="loop" className="loop-section"><div className="loop-heading"><p className="kicker">Designed maintenance loop</p><h2>Notes stay current by design, with a human in the loop.</h2><p>This demo illustrates the operating model. It does not represent a live autonomous agent.</p></div><ol className="loop"><li><b>New drawing lands</b><span>Agent reads the drawing, spec sheet, or QR payload.</span></li><li><b>Records update</b><span>Fields and linked entities are proposed from the source.</span></li><li><b>Conflicts surface</b><span>Changed tolerances, material, or revisions are flagged for review.</span></li><li><b>Human releases</b><span>Approved changes become the current record and leave an audit trail.</span></li></ol><div className="loop-note"><Sparkles size={18}/><span><strong>What the agent maintains:</strong> traceable notes, connected entities, and exception queues — not unreviewed shop-floor truth.</span></div></section><footer><span>ARCH GP · manufacturing knowledge demo</span><span>Illustrative content only · no customer or production data</span></footer></main>
}
export default App
